---
spring:
  config:
    import: "optional:configserver:http://localhost:8001"

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

words: fallback

# Expose actuator endpoints

management.endpoints.web.exposure.include: health,info,beans,env,configprops,mappings
management.info:
  env.enabled: true
  java.enabled: true
  os.enabled: true
  process.enabled: true
info.active-profiles: ${spring.profiles.active:none}
info.name: ${spring.application.name:none}

# Set a different name depending on the profile

---
spring:
  config.activate.on-profile: subject
  application:
    name: subject

---
spring:
  config.activate.on-profile: verb
  application:
    name: verb

---
spring:
  config.activate.on-profile: article
  application:
    name: article

---
spring:
  config.activate.on-profile: adjective
  application:
    name: adjective

---
spring:
  config.activate.on-profile: noun
  application:
    name: noun

---
spring:
  config.activate.on-profile: cold-noun
  application:
    name: noun
words: icicle,refrigerator,blizzard,snowball